src/pack_x64.s
src/pack_x86.s
src/unpack_armv7.s
src/unpack_x64.s
src/unpack_x86.s

We have received a bug report mentioning that the shared library is built with an executable stack (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793320 for more details). This PR contains a patch by Russell Coker to remove the executable bit.

Mark stack as non-executable

---

src/unpack_armv7.s

Build originally failed with:
[..]
unpack_armv7.s: Assembler messages:
unpack_armv7.s:1: Error: junk at end of line, first unrecognized
character is `/'
unpack_armv7.s:2: Error: junk at end of line, first unrecognized
character is `/'
unpack_armv7.s:3: Error: junk at end of line, first unrecognized
character is `/'
unpack_armv7.s:4: Error: junk at end of line, first unrecognized
character is `/'
unpack_armv7.s:5: Error: junk at end of line, first unrecognized
character is `/'
unpack_armv7.s:6: Error: junk at end of line, first unrecognized
character is `/'
unpack_armv7.s:7: Error: junk at end of line, first unrecognized
character is `/'
Makefile:661: recipe for target 'unpack_armv7.lo' failed
[..]

Fix build for armv7, GNU as uses @ for single-line comments on ARM

---

.travis.yml

if you're interested, you could enable travis ci on this repo (https://travis-ci.org/stephengroat/WavPack). I know that i currently only have a very small subset of tests running, but I'm not 100% sure how to get the granularity I need for travis (maximum # of jobs is 200, maximum runtime on each job is 50 mins). More tests could be specific by creating more versions of the `WVTEST_ARGS` environment variable
If you're interested, let me know, i'd be interested in helping.
Also could enable automated Windows builds with [appveyor](https://www.appveyor.com/)

enable travis ci build and testing

---

configure.ac

ARM assembly in wavpack is armv7 only it seems.
I have reports this causes build failures on armv5: https://bugs.gentoo.org/show_bug.cgi?id=609168

configure: Restrict arm assembly to armv7 only.

---

src/decorr_utils.c
src/entropy_utils.c
src/open_legacy.c
src/open_utils.c
src/tag_utils.c
src/tags.c
src/unpack3.c
src/unpack3_open.c
src/unpack_dsd.c
src/unpack_seek.c
src/unpack_utils.c

In order to compile the C code in a C++ project, I've had to C-style cast anything that was of type `void*` to the destination type.
The issue we were running into is the blasted [error C2440](https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(C2440)&rd=true).
A bit of background: I'm a C++ developer using [JUCE](https://github.com/WeAreROLI/JUCE). In-house at [AudioWorks](https://github.com/Audioworks) we have our own [Unity Build modules](http://buffered.io/posts/the-magic-of-unity-builds/), following similar conventions to JUCE's modules.
We are trying to use this repository as a submodule in order to avoid the whole _Not Invented Here_ problem, and having a facilitated way of keeping up to date. To do this, we have wrapped WavPack's source in a derived …

Fixed compilation errors when using a C++ compiler.

---

src/extra1.c
src/extra2.c
src/pack.c
src/pack_x64.S
src/unpack.c
src/unpack_x64.S
src/wavpack_local.h

This adds support for building on midipix with the manually written ASM routines, only 64-bit version for now, as 32-bit doesn't compile yet, so I can't test it...

x64 ASM support for midipix

---

cli/Makefile.am

The `.libs` directory is an internal libtool directory which build projects should not directly use. With libtool it will happen to work because it parses the actual file, but with other implementations such as slibtool it will fail because it relies a `.deps` file found in the same directory as the `.la` file which will not be found.
Instead of using the the symlinked `.la` file in the `.libs` directory its better to use the file the symlink points to and this will allow greater portability for building WavPack.
For reference here is the current build error with slibtool:
```
rdlibtool --tag=CC --mode=link gcc -I../include -g -O2 -o wavpack wavpack-wavpack.o wavpack-riff.o wavpack-wave64.o wavpack-caff.o wavpack-dsdiff.o wavpack-dsf.o wavpack-utils.o wavpack-md5.o wavpack-import_id3.o …
```

cli: Fix build with slibtool.

---

include/wavpack.h
src/Makefile.am
src/libwavpack.vcproj
src/wavpack_local.h
wavpackdll/wavpackdll.vcproj

The goal is to remove duplicated code from `wavpack.h` & `wavpack_local.h`. `WavPackContext` is still opaque pointer for library users, but for private use it is typedef to internal struct.
* Include `wavpack.h` to `wavpack_local.h`
* `WavPackContext` is now typedef of struct `WavPackContext` in
`wavpack_local.h`
* Remove duplicates from `wavpack_local.h`

Optimize wavpack.h

---

src/read_words.c

This should eliminate the _implicit declaration_ warning during MinGW build. MinGW has the `__builtin_ctz` function and defines `_WIN32` too. By some unknown magic it produces working executable even without the change, but with the change we get rid of the warning and the produced executable is a little bit smaller.
BTW here
https://github.com/dbry/WavPack/blob/a07f314ae89092362211a6f982e27c83febec086/src/read_words.c#L32
you restrict `_BitScanForward` only to win64 not sure why, i think it should work for win32 too (haven't tested though).

restrict _BitScanForward to msvc

---

CMakeLists.txt

CMake detects 32-bit masm in 64-bit, hell knows why. Fixed now.

CMake: fix MASM 64-bit detection #51

---

configure.ac

$enableval should be used to know if the user has passed --enable-man or
--disable-man
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

configure.ac: fix --disable-man

---

.travis.yml
Makefile.am
cli/Makefile.am
cli/all-tests
cli/fast-tests
configure.ac
man/Makefile.am

Hi @dbry 
Here are a few updates to make the Autotools build system POSIX compatible so it can be used with shell like Dash and Make implementations such as `bmake` and `pmake`. Furthermore, I've implemented the test to use the normal automake test harness, which means it can be invoked with `make check` instead of invoking the binary directly. This massively simplifies the packaging for us downstream in the distributions.

Autotools update

---

configure.ac

@SoapGentoo I found a very minor issue with the new configure script where it would require iconv even for Windows builds (which use a native Windows API instead). This patch removes that dependency but I wanted to run it by you because I have no idea what I'm doing. Thanks.

iconv is not used in Windows builds, so don't require in configure

---

configure.ac

* POSIX calls the `-a` and `-o` operators obsolescent
and strongly discourages their use, instead recommending
chaining `test` calls instead:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html

Avoid obsolescent `test -a` constructs

---

audition/cool_wv4.c

```
audition/cool_wv4.c: In function 'FilterGetOptions':
audition/cool_wv4.c:772:5: warning: passing argument 4 of 'DialogBoxParamA' from incompatible pointer type
winuser.h:2240:29: note: expected 'DLGPROC' but argument is of type 'BOOL (*)(struct HWND__ *, UINT,  WPARAM,  LPARAM)'
audition/cool_wv4.c: In function 'WavPackDlgProc':
audition/cool_wv4.c:836:77: warning: cast from pointer to integer of different size
```

audition/cool_wv4.c: fix warnings from win64 builds

---

autogen.sh

This otherwise gets in the way of being able to do out of tree builds when making use of autogen.sh.

autogen: Honour NOCONFIGURE=1

---

src/extra1.c
src/extra2.c
src/tag_utils.c
src/wavpack_local.h

fixes warnings from WatcomC (Open Watcom):
```
extra1.c(237): Warning! W115: &array may not produce intended result
extra1.c(556): Warning! W115: &array may not produce intended result
extra1.c(611): Warning! W115: &array may not produce intended result
extra2.c(396): Warning! W115: &array may not produce intended result
extra2.c(650): Warning! W115: &array may not produce intended result
extra2.c(746): Warning! W115: &array may not produce intended result
extra2.c(818): Warning! W115: &array may not produce intended result
tag_utils.c(529): Warning! W115: &array may not produce intended result
```

eliminate use of '&' address-of operator on arrays:

---

src/extra1.c
src/extra2.c
src/pack.c
src/unpack.c
src/wavpack_local.h

`__cdecl` isn't default calling convention for Watcom.  This handles calling convention and also symbol decoration correctly.

mark x86 asm functions as __cdecl for Watcom compiler :

---

cli/aiff.c
cli/utils.c
cli/wvparser.c
cli/wvunpack.c
src/open_filename.c
winamp/in_wv.c

- cli/aiff.c: eliminate declaration-after-statement for c89 compilers
- cli/aiff.c: lose c99 vla and use a fixed [256] array for `compressionName`
- silence incompatible pointer warning for `GetFileSize()`.
- cli/utils.c: define `_WIN32_WINNT` as `0x0500` for `GetConsoleWindow()`.
- win32: don't define `fileno` as `_fileno` to avoid possible errors/warnings

miscellaneous build / warning fixes:

---

src/read_words.c
src/wavpack_local.h

Uses `bsr` and `bsf` inline asm in watcom aux pragma syntax.
Question: these optimizations are not enabled in MSVC 32 bit
builds: is there a reason?

enable clz and ctz optimizations for watcom builds.

---

CMakeLists.txt
winamp/in_wv.c

- the plugin dll must be named 'in_wv.dll' without 'lib' prefix.
- the 'lng' file is now built (was missing the 'LINKER_LANGUAGE' property), and is correctly named (*.lng, not *.lang) matching the MSVC project file.

cmake: fixes to winamp plugin build

---

CMakeLists.txt
wavpackdll/wavpackdll.rc
wavpackdll/wavpackdll.vcxproj

- Some MSVC configurations did not export `WavpackFloatNormalize`.
- In my last pr, I converted the library types to MODULE. Looks like one needs to set the `OUTPUT_NAME` property on them.
- I don't have MFC installed on my system, so I changed `#include <windows.h>` to `#include <windows.h>`.
Everything keeps building. But I'm no expert in MFC stuff.
With these changes, running `dumpbin /exports` on the dll's, lng's or flt's give me no difference in exported symbols.

CMake + MSVC fix

---

CMakeLists.txt

With these fixes, I am able to let the WavPack Decoder plug-in appear in WinAMP.
Proof:
- By adding the objects of wavpack to `in_wv.dll` instead of linking to it, you don't need to copy the `wavpackdll.dll` to the winamp folder. Copying `wavpackdll.dll` to the `Plugins` folder wasn't enough, you had to copy it to the folder containing the winamp executable. By embedding wavpack in `in_wv.dll`, there are no more external dependencies.
- Link to static libgcc and libstdc++ to avoid needing the GNU standard library in a public location.
I suppose cooledit suffers from similar issues.

CMake fixes for WinAMP

---

audition/Makefile.wat
winamp/in_wv.c
winamp/wasabi/Winamp/wa_ipc.h

- add OpenWatcom makefile to build Win32 CoolEdit plugin.
- use prototyped function ptrs instead of an opaque FARPROC
(same as https://github.com/dbry/WavPack/pull/140, but for winamp plugin.)
- winamp/wa_ipc.h: replace UNREFERENCED_PARAMETER(item) with (void)(item)
win32 sdk defines `UNREFERENCED_PARAMETER(item)` as `(item)` which generates
warnings with other compilers.
- winamp plugin, truncate_here(): watcom clib support
Not adding a watcom makefile for winamp plugin because the result is reported
to crash in ticket #146.
(Question: One curious thing in winamp plugin is that its reader passes pointers to `FILE*`
pointers instead just just the `FILE*` pointers themselves. Any specific reason??)

misc patches to plugins:

---

cli/wavpack.c
cli/wvunpack.c

```
cli/wavpack.c: In function 'main':
cli/wavpack.c:350:5: warning: 'strncpy' specified bound 4096 equals destination size [-Wstringop-truncation]
350 |     strncpy (selfname, *argv, sizeof (selfname));
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cli/wvunpack.c: In function 'main':
cli/wvunpack.c:288:5: warning: 'strncpy' specified bound 4096 equals destination size [-Wstringop-truncation]
288 |     strncpy (selfname, *argv, sizeof (selfname));
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Silence gcc-9 -Wstringop-truncation warnings:

---

CMakeLists.txt
configure.ac

- configure.ac already has `-Wall` in `AM_INIT_AUTOMAKE` options,
but it does _not_ affect the compiler:
https://stackoverflow.com/questions/22152738
- cmake, on the other hand, doesn't have any warning options set,
this patch does that along with autotools. (CC: @madebr)

autotools, cmake: add -Wall to CFLAGS for gcc (or clang)

---

cli/utils.c

fixes this build error:
```
utils.c(581): Error! E1054: Expression must be constant
utils.c(581): Error! E1054: Expression must be constant
```

fix build with watcom compiler

---

CMakeLists.txt

This only changes the default when using wavpack as a subproject.
It is always possible to explicitly build the programs by configuring with `-DWAVPACK_BUILD_PROGRAMS=ON`.
I did not touch all options, as some are useful to have enabled by default.
@redtide
FIxes #163

cmake: don't enable tests and programs when building wavpack as a subproject

---

CMakeLists.txt
Makefile.am
configure.ac

- autotools: add version resource to libwavpack windows builds.
- autotools: link libcryto only to its users, not everything.
- autotools: don't link with pthread when targeting windows where it's
not used and need not be available.
- cmake: fix openssl/libcrypto usage: it minked it to libwavpack where
it isn't used and not the programs where it actually matters.
- cmake: bumped minimum required version to 3.5 to ease the use of ssl
options.
- cmake: disable libcrypto by default so it matches autotools and it's
noted that it breaks macOS builds.
- cmake: fix the purpose description of openssl package.
- cmake: only do find_package(Threads) for non-windows: otherwise it'd
find pthreads which may be available in mingw toolchains.
Build tested using autotools and cmake targeting linux and …

fix several build issues, add version res to autotools windows builds.

---

CMakeLists.txt
Makefile.am
cli/md5.c
cli/md5.h
configure.ac

It isn't a part of libwavpack, only used if you specify -m or -v on the program command-line, makes only a negligible difference in performance. It causes trouble for Apple too because the API is different. Therefore, it's not worth the complexity.

remove optional openssl libcrypt dependency.

---

Makefile.am

(was missed in c01d06d3f969ae7cd0bb32e95271ca189dce1840)

Makefile.am: add src/wavpack.exports to EXTRA_DIST

---

src/open_filename.c

As discussed at https://github.com/dbry/WavPack/commit/99f63f0c9a670fde92e809a0e49213945dfbae79#commitcomment-131286647
Created this PR so that it won't get lost.

use _fstati64 in can_seek and get_length for windows (or with watcom.)

---

src/decorr_utils.c
src/extra1.c
src/extra2.c
src/open_utils.c
src/pack.c
src/read_words.c
src/unpack3.c
src/unpack3.h
src/unpack3_seek.c
src/write_words.c

This is an extension of PR #130, where the compiler missed several
cases because of a bug [1]. (These ones were revealed by using the
c++ compiler instead.)
[1] https://github.com/open-watcom/open-watcom-v2/issues/1158

eliminate use of '&' address-of operator on arrays (take/2.)

---

CMakeLists.txt
cmake/wavpackcpu.cmake

With this patch, I was able to build arm64 Windows executables, for inclusion in SDL3_mixer binary VC releases.
The `wavpackcpu.cmake` script is a copy of SDL's `sdlcpu.cmake`, with "SDL" replaced with `WavPack`.
`CMAKE_SYSTEM_PROCESSOR` is always `AMD64`, even when building wavpack with an arm64 MSVC toolchain.
FYI Microsoft ARM assembler support in CMake uses the `ASM_MARMASM` language.
The MS ARM assembler is not 100% compatible with a GNU ARM assembler.
Luckily, I didn't encounter this issue when building a arm64 wavpack library, but it's something to take into account.
(I didn't test building `src/unpack_armv7.S` for 32-bit arm windows. Windows on 32-bit arm will never happen)

cmake: CMAKE_SYSTEM_PROCESSOR is the architecture of the build machine

---

cli/utils.c

Follow-up to 8b5b1f54863c2b3b2d578d3c4c8434a7447134e5. macOS does not have `sys/sysinfo.h`, nor does it have `get_nprocs(3)`. On macOS, use `sysctlbyname(3)` in `sys/sysctl.h` instead.
This change addresses #195. I have tried to scope the preprocessor macros as narrowly as possible, so as to avoid impacting other *nix distributions. Note that `sys/sysinfo.h` and `get_nprocs(3)` are Linux extensions, not standardized by POSIX (although some ports of it to e.g. FreeBSD might exist). So I suspect some other *nix platforms may also be impacted by the aforementioned commit.

cli: support detecting cores in macOS and BSDs

---

src/read_words.c
src/wavpack_local.h

also remove clang-cl restriction in read_words.c and always include intrin.h for MSVC.

include intrin.h in MSVC builds for BitScanXXX.

---

.github/workflows/build.yml
Makefile.am
configure.ac

Since gettext 0.25, the AM_ICONV macro is installed into the m4 directory, so we need to add that autoconf config directory.  We also need to make sure autoreconf recognizes that it needs to run autopoint to install the gettext macros, which it does heuristically by checking whether AM_GNU_GETTEXT_VERSION is used, so add that and the minimum amount of other stuff required to make it happy.  The version of gettext we say we use shouldn't matter, so I just went with the version in ubuntu:latest since that's what CI uses.

Fix autoreconf with gettext 0.25

---

cli/wvunpack.c

proper variable name in expression

wvunpack.c: fix the message about extra/missing samples
